### ISSUE TITLE
(Werror) clang 8.0.0 build error

### ISSUE THREAD

**Issue by orbea** [LIJI32/SameBoy#172]
OS: `Slackware64-current`
Compiler: `clang-8.0.0`
SameBoy: https://github.com/LIJI32/SameBoy/commit/10be34b5b252711d961ac13a6b8417cb1b94d2bb

I tried to build SameBoy standalone with `clang-8.0.0` and recieved this error.
```
Core/apu.c:69:13: error: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Werror,-Wpass-failed=transform-warning]
static void render(GB_gameboy_t *gb, bool no_downsampling, GB_sample_t *dest)
            ^
1 error generated.
make: *** [Makefile:161: build/obj/Core/apu.c.o] Error 1
```
LOG: [SameBoy.log](https://github.com/LIJI32/SameBoy/files/3159053/SameBoy.log)

Maybe it would be good to not force `-Werror`? This just makes it likely to break on new compilers for what might be an otherwise benign warning.

**Comment by LIJI32** [comment]
It's actually a good thing this warning triggered. Unless it fails silently and I'm misremembering something, this optimization does work on my machine and it significantly improves performance. It should be actually fixed and not worked around.

**Comment by orbea** [comment]
Do you know how to fix it? I've never seen this warning before... It would be nice if building SameBoy with clang was also supported. :)

**Comment by LIJI32** [comment]
Well, Clang *is* the recommended compiler to use for SameBoy, and the compiler I use for all official builds (Although I use Apple's fork for macOS, and an older version of it), which is why it's weird. You can disable Werror as a workaround but I'll have to properly investigate it.

**Comment by orbea** [comment]
You're right, I unset the `CC` and `CXX` and SameBoy uses clang by default. Additionally SameBoy unfortunately outright ignores these variables even if I set them to gcc and g++.

Also this warning was introduced sometime after `v0.11.2`.

**Comment by orbea** [comment]
And gcc9 has this issue.
```
Core/display.c:30: error: ignoring #pragma unroll  [-Werror=unknown-pragmas]
   30 |         #pragma unroll
      | 
Core/display.c:46: error: ignoring #pragma unroll  [-Werror=unknown-pragmas]
   46 |         #pragma unroll
      | 
Core/display.c: In function ‘fifo_overlay_object_row’:
Core/display.c:73: error: ignoring #pragma unroll  [-Werror=unknown-pragmas]
   73 |     #pragma unroll
      | 
Core/display.c: In function ‘GB_get_oam_info’:
Core/display.c:1120: error: ignoring #pragma unroll  [-Werror=unknown-pragmas]
 1120 |             #pragma unroll
      | 
Core/display.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]
cc1: all warnings being treated as errors
Core/apu.c: In function ‘render’:
Core/apu.c:72: error: ignoring #pragma unroll  [-Werror=unknown-pragmas]
   72 |     #pragma unroll
      | 
Core/apu.c:129: error: ignoring #pragma unroll  [-Werror=unknown-pragmas]
  129 |             #pragma unroll
      | 
Core/apu.c: In function ‘GB_apu_run’:
Core/apu.c:377: error: ignoring #pragma unroll  [-Werror=unknown-pragmas]
  377 |     #pragma unroll
      | 
Core/apu.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]
cc1: all warnings being treated as errors
make: *** [Makefile:162: build/obj/Core/display.c.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:162: build/obj/Core/apu.c.o] Error 1
```

**Comment by orbea** [comment]
The issue with clang only occurs with `make CONF=release`.

It started here.
```
9d947c7ce639e93f42a86d1bf42135ff78f0375a is the first bad commit
commit 9d947c7ce639e93f42a86d1bf42135ff78f0375a
Author: Lior Halphon <LIJI32@gmail.com>
Date:   Mon Dec 31 23:09:56 2018 +0200

    Unroll some APU loops

:040000 040000 a60e0012c651b88fb81253ac0817882922ecce37 ad7eed081e24492ddc4da94ea04477119fce226a M	Core
```
9d947c7ce639e93f42a86d1bf42135ff78f0375a

**Comment by orbea** [comment]
Commenting this line allows the build with clang to succeed.

https://github.com/LIJI32/SameBoy/blob/9d947c7ce639e93f42a86d1bf42135ff78f0375a/Core/apu.c#L72

**Comment by orbea** [comment]
Here is a similar issue with another project, unfortunately it doesn't offer much info.

https://github.com/ROCmSoftwarePlatform/rocPRIM/commit/353a794b1b128226a18c438f4d9b72349433f648

The clang documentation is also unhelpful.

> The text of this diagnostic is not controlled by Clang.

https://clang.llvm.org/docs/DiagnosticsReference.html#wpass-failed

**Comment by orbea** [comment]
This might be related to amdgpu.

https://github.com/pytorch/pytorch/pull/16808#issuecomment-461260551

**Comment by funbars** [comment]
GB_N_CHANNELS is known const. Maybe compile-time inline with templates? Or alternate pragma?

```#pragma clang loop unroll_count(GB_N_CHANNELS)```

**Comment by orbea** [comment]
The alternate pragma resulted in the same error. I am not sure how to try the former suggestion. If this is related to amdgpu I wonder if a newer kernel will help, I'll try that.

**Comment by LIJI32** [comment]
It look that Clang just refuses the unroll that specific loop, on the version I use it just fails silently.

**Comment by funbars** [comment]
This fixed Clang, just before https://github.com/LIJI32/SameBoy/commit/06670fc970dd1cfb2695534fc6e4d92ed5a632f2

```for (unsigned i = GB_N_CHANNELS; i--;) {```

to

```for (unsigned i = 0; i < GB_N_CHANNELS; i++) {```

**Comment by LIJI32** [comment]
Looks like it does, I restored the optimization. Thanks!
